version: '3'
services:
  php:
    image: php:7.4-cli
    container_name: pex_php
    command: tail -f /dev/null
    working_dir: /var/www/pex
    volumes:
      - .:/var/www/pex:cached
  composer:
    image: composer:1.10.10
    container_name: pex_composer
    command: composer install
    volumes:
      - .:/app:delegated